[build]
builder = "nixpacks"

[deploy]
startCommand = "cd Backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environment]
# Server Configuration
NODE_ENV = "production"
PORT = "5000"
HOST = "0.0.0.0"

# JWT Configuration
JWT_EXPIRE = "24h"

# File Upload Configuration
MAX_FILE_SIZE = "10485760"
UPLOAD_PATH = "./uploads"

# Admin Configuration
ADMIN_USERNAME = "Admin"
ADMIN_EMAIL = "admin@sodeclick.com"

# Security Configuration
BCRYPT_ROUNDS = "12"

# Rate Limiting
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"

# Logging Configuration
LOG_LEVEL = "info"
LOG_FILE = "./logs/app.log"

# Health Check Configuration
HEALTH_CHECK_TIMEOUT = "5000"
HEALTH_CHECK_INTERVAL = "30000"

# Note: Sensitive variables like MONGODB_URI, JWT_SECRET, ADMIN_PASSWORD
# should be set in Railway Dashboard Environment Variables, not here