[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = ['npm install --production=false']

[phases.build]
cmds = ['npm run build:backend || true']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production' 